[build]
  command = "npm run build"   # Build command for React
  publish = "build"           # Directory to publish after build

[build.environment]
  NODE_VERSION = "20"         # Adjust to the Node.js version you're using
  REACT_APP_API_URL = "https://your-api-url.com"
  REACT_APP_CHAIN_ID = "your-chain-id"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://your-api-url.com; img-src 'self' data:; style-src 'self' 'unsafe-inline';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
